# Generated by Django 4.2 on 2023-05-04 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='donation',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='donation',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
